# Generated by Django 4.0.4 on 2023-02-20 19:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='letter',
            fields=[
                ('id', models.BigAutoField(db_column='letter_id', primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=10, verbose_name='보내는 사람')),
                ('title', models.CharField(max_length=50, verbose_name='편지 제목')),
                ('content', models.TextField(verbose_name='편지 내용')),
                ('sendAt', models.DateTimeField(default=datetime.datetime(2023, 2, 20, 19, 43, 41, 464727))),
                ('isOpened', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'letter',
            },
        ),
    ]
