# Generated by Django 4.0.4 on 2023-02-23 16:15

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_alter_letter_sendat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='receiver',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 16, 15, 52, 373843)),
        ),
    ]
