# Generated by Django 4.0.4 on 2023-02-23 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0010_alter_letter_sendat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='receiver',
            new_name='receiver_username',
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 20, 35, 1, 325108)),
        ),
    ]
