# Generated by Django 4.0.4 on 2023-02-23 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0011_rename_receiver_letter_receiver_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='receiver_username',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 20, 37, 10, 934501)),
        ),
    ]
