# Generated by Django 4.0.4 on 2023-02-24 00:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letterapp', '0012_rename_receiver_username_letter_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 0, 5, 0, 836149)),
        ),
    ]
