# Generated by Django 4.0.4 on 2023-02-24 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0014_alter_letter_receiver_alter_letter_sendat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 0, 17, 2, 674029)),
        ),
    ]
